#!/bin/sh
set -x
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
#
# Copyright 2013 Steffen Kram. All rights reserved.
# Use is subject to license terms.
#
. /lib/svc/share/smf_include.sh

getproparg() {
    val=`svcprop -p $1 $SMF_FMRI`
    [ -n "$val" ] && echo $val
}

#basedir=`getproparg mysql_56/base`
#bindir=`getproparg mysql_56/bin`
#sbindir=$bindir
#libexecdir=$bindir
#datadir=`getproparg mysql_56/data`
#mycnf=`getproparg mysql_56/mycnf`
#socket=`getproparg mysql_56/socket`
#mysql_pid=`getproparg mysql_56/pidfile`


if [ -z $SMF_FMRI ]; then
    echo "Error: SMF framework variables are not initialized"
    exit $SMF_EXIT_ERR
fi

#if [ -z $basedir ]; then
#    echo "Error: mysql_56/base property not set"
#    exit $SMF_EXIT_ERR_CONFIG
#fi

case "$1" in
'start')
    /usr/bin/java -jar /usr/local/lib/knx-logger/MyKnxReader-1.0-SNAPSHOT-jar-with-dependencies.jar -f /etc/knx-logger/ga.csv -g 192.168.178.1 -j jdbc:mysql://localhost:3306/ZZZZZZZZ -u YYYYYYYYYY -p XXXXXXX &
    ;;

'stop')
    ;;

'reload')
    ;;

*)
    echo "Usage: $0  {start|stop|reload} "
    exit 1
    ;;
esac
exit 0
